In [ ]:
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  
  
# Importing the dataset  
dataset = pd.read_csv('/content/drive/MyDrive/pima-indians-diabetes.csv')  
x = dataset.iloc[:,[2,3]].values  
y = dataset.iloc[:, -1].values  
  
# Splitting the dataset into the Training set and Test set  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.40, random_state = 0)  
  
# Feature Scaling  
from sklearn.preprocessing import StandardScaler  
sc = StandardScaler()  
x_train = sc.fit_transform(x_train)  
x_test = sc.transform(x_test)  
x_train

array([[-3.58463583,  0.13838914],
       [ 0.86648296, -1.33312558],
       [ 0.29715381, -1.33312558],
       [-0.58271851,  0.65022035],
       [-0.06514656, -0.50139986],
       [ 1.28054052, -1.33312558],
       [-0.16866095, -0.37344206],
       [ 0.24539661,  1.09807266],
       [ 0.14188222, -0.18150536],
       [ 0.81472576,  0.26634695],
       [ 0.65945418,  0.71419925],
       [-0.22041814,  0.45828365],
       [-3.58463583,  0.58624145],
       [ 1.07351174,  0.77817815],
       [ 0.86648296,  0.65022035],
       [-0.27217534,  0.97011486],
       [ 0.03836783,  0.58624145],
       [-0.37568973,  0.58624145],
       [ 0.03836783,  0.45828365],
       [ 0.24539661,  0.07441024],
       [ 0.348911  , -0.05354756],
       [ 0.4524254 ,  0.39430475],
       [-0.16866095, -0.37344206],
       [ 0.03836783, -1.33312558],
       [ 0.14188222, -1.33312558],
       [ 0.96999735,  1.03409376],
       [-3.58463583, -1.33312558],
       [-1.51434802,  0.90613596],
       [-0.47920412,

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Fitting Naive Bayes to the Training set  
from sklearn.naive_bayes import GaussianNB  
classifier = GaussianNB()  
classifier.fit(x_train, y_train)  

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred = classifier.predict(x_test)  
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,

In [ ]:
# Making the Confusion Matrix  
from sklearn.metrics import confusion_matrix  
cm = confusion_matrix(y_test, y_pred) 
cm 

array([[194,  10],
       [ 95,   8]])